### PR TITLE
Improve streamr json and enable transitive monorepo dependencies

### PR DESCRIPTION
**Pull request by ptesavol**
* Support std::initializer_list inputs that contain arbitrary structs in toJson()
* Support pointer types in toJson()
* Add nullptr safety to toJson()
* Support transitive monorepo dependencies: (streamr-proto-rpc depends on streamr-logger which depends on streamr-json)

**TODO: Move JsonBuilder and other code that should not be used by users to details**

### CODE REVIEW

**Comment by SanttuRantanen** [comment]
It looks good for me. I have just a few comments.

1. Why boost traits are used? Are there any similar standard library traits?
2. Please remove the commented code:

JsonBuilder.hpp:

                            // implicit conversion
        // static_assert(!std::is_pointer_v<T>, "Pointers cannot be converted to
        // JSON");
        /*
        if constexpr (std::is_pointer_v<T>) {
            if (&value == 0) {
                jsonData = nullptr;
            }
            else {
                jsonData = "<pointer>";
            }
        }
        */


/*
requires(T value) {
    { std::is_assignable<JsonBuilder&, T>::value };
    //requires(not AssociativeType<T>);
    //requires(not IterableType<T>);
    requires(not TypeWithToJson<T>);
    requires(not AssignableToNlohmannJson<T>);
};*/

jsonConcepts.hpp:

// template <typename T>
// concept NotAssignableToJson = !std::is_assignable<nlohmann::json&, T>::value;



/*
template <typename T>
concept OtherInitializerList = requires(T obj) {
    requires(not AssociativeType<T>);
    requires(not IterableType<T>);
    requires (not TypeWithToJson<T>);
    requires (not AssignableToNlohmannJson<T>);
    requires (noaland::is_fuzzy_type_matched_v<T,
std::initializer_list<noaland::i_dont_care>>);
};
*/

**Review by SanttuRantanen — APPROVED** [review]
It looks good for me. I have just a few comments.

Why boost traits are used? Are there any similar standard library traits?
Please remove the commented code:
JsonBuilder.hpp:

                        // implicit conversion
    // static_assert(!std::is_pointer_v<T>, "Pointers cannot be converted to
    // JSON");
    /*
    if constexpr (std::is_pointer_v<T>) {
        if (&value == 0) {
            jsonData = nullptr;
        }
        else {
            jsonData = "<pointer>";
        }
    }
    */
/*
requires(T value) {
{ std::is_assignable<JsonBuilder&, T>::value };
//requires(not AssociativeType);
//requires(not IterableType);
requires(not TypeWithToJson);
requires(not AssignableToNlohmannJson);
};*/

jsonConcepts.hpp:

// template
// concept NotAssignableToJson = !std::is_assignable<nlohmann::json&, T>::value;

/*
template
concept OtherInitializerList = requires(T obj) {
requires(not AssociativeType);
requires(not IterableType);
requires (not TypeWithToJson);
requires (not AssignableToNlohmannJson);
requires (noaland::is_fuzzy_type_matched_v<T,
std::initializer_listnoaland::i_dont_care>);
};
*/

**Comment by ptesavol** [comment]
1. Boost is used because it offers reflection of field names of structs. This is not yet supported by the standard library

**Comment by ptesavol** [comment]
2. Commented code removed. Also added a comment on how JsonBuilder works.

**Pull request merged**
